#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='delete references with ax-'
FILE='../../bins/elf/crackme'
ARGS=
CMDS='
ax 10 20
ax
ax- 10
ax
ax- 20
ax
ax 10 20
ax 30
ax
ax-*
ax
'
EXPECT='ref.unk.0x14=0xa
xref.unk.0xa=0x14
types=code.jmp,code.call,data.mem,data.string
ref.unk.0x14=0xa
xref.unk.0xa=0x14
types=code.jmp,code.call,data.mem,data.string
types=code.jmp,code.call,data.mem,data.string
ref.unk.0x14=0xa
xref.unk.0xa=0x14
xref.unk.0x1e=0x4005c0
ref.unk.0x4005c0=0x1e
types=code.jmp,code.call,data.mem,data.string
types=code.jmp,code.call,data.mem,data.string
'
run_test

